version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./nginx-data/certs:/etc/nginx/certs
      - ./nginx-data/vhost.d:/etc/nginx/vhost.d
      - ./nginx-data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}

  memcached:
    image: memcached:latest
    container_name: memcached-piler
    restart: unless-stopped
    cap_drop:
      - ALL
    command: -m 64

  piler:
    image: simatec/piler:${PILER_VERSION}
    container_name: piler
    restart: unless-stopped
    expose:
      - "80"
    hostname: ${PILER_DOMAIN}
    init: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - PILER_HOSTNAME=${PILER_DOMAIN}
      - MEMCACHED_HOST=memcached
      - TZ=${TIME_ZONE}
      - VIRTUAL_HOST=${PILER_DOMAIN}
      - LETSENCRYPT_HOST=${PILER_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - "${SMTP_PORT}:25"
    volumes:
      - piler_etc:/etc/piler
      - piler_var_store:/var/piler/store
      - piler_var_manticore:/var/piler/manticore
      - piler_var_imap:/var/piler/imap
      - piler_var_stat:/var/piler/stat
      - piler_cron:/var/spool/cron/crontabs
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: curl -s smtp://localhost/
      interval: "60s"
      timeout: "3s"
      start_period: "15s"
      retries: 3
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 512M

    depends_on:
      - "memcached"

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  piler_etc:
  piler_var_store:
  piler_var_manticore:
  piler_var_imap:
  piler_var_stat:
  piler_cron:
